[package]
name = "orbit"
version = "0.1.0"
authors = ["Andreas C. Osowski <andreas.chr.osowski@gmail.com>"]

[dependencies]
regex = "*"
regex_macros = "*"
docopt = "*"
docopt_macros = "*"
rustc-serialize = "*"
roots = "*"
chrono = "*"
sdl2 = "0.18.0"
sdl2_gfx = "0.18.0"
